name: PickSpawner
authors: [fabien91]
version: ${version}
main: fr.fabienhebuterne.pickspawner.PickSpawner
depend: [Vault]
# Kotlin isn't included in PickSpawner so we need loader plugin to load kotlin before current plugin
softdepend:
  - eco
api-version: 1.18

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.10
  - org.jetbrains.kotlin:kotlin-reflect:1.7.10

commands:
   pickspawner:
     description: PickSpawner base command
     aliases: [picks, ps, pspawner]
