name: PickSpawner
authors: [fabien91]
version: ${version}
main: fr.fabienhebuterne.pickspawner.PickSpawner
depend: [Vault]
api-version: 1.18

commands:
   pickspawner:
     description: PickSpawner base command
     aliases: [picks, ps, pspawner]
