name: PickSpawner
authors: [fabien91]
version: ${version}
main: fr.fabienhebuterne.pickspawner.PickSpawner
depend: [Vault]
api-version: 1.18

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.22
  - org.jetbrains.kotlin:kotlin-reflect:1.9.22

commands:
   pickspawner:
     description: PickSpawner base command
     aliases: [picks, ps, pspawner]
